export const DRIVER_NAMES = [
    'Lewis Hamilton',
    'Max Verstappen',
    'Valtteri Bottas',
    'Sergio Perez',
    'Lando Norris',
    'Charles Leclerc',
    'Carlos Sainz',
    'Oscar Piastry',
    'Esteban Ocon',
    'Fernando Alonso',
    'Nyck De Vries',
    'Lance Stroll',
    'Yuki Tsunoda',
    'George Russell',
    'Logan Sargeant',
    'Nico Hulkenberg',
    'Zhou Guanyu',
    'Alexander Albon',
    'Kevin Magnussen',
    'Pierre Gasly',
]