export const DRIVER_NAMES = [
    "Max Verstappen",
    "Liam Lawson",
    "Charles Leclerc",
    "Lewis Hamilton",
    "George Russell",
    "Andrea Kimi Antonelli",
    "Lando Norris",
    "Oscar Piastri",
    "Fernando Alonso",
    "Lance Stroll",
    "Pierre Gasly",
    "Jack Doohan",
    "Alex Albon",
    "Carlos Sainz",
    "Yuki Tsunoda",
    "Isack Hadjar",
    "Oliver Bearman",
    "Esteban Ocon"
    ];